vich_uploader:
    db_driver: orm

    mappings:
        shops_image:
            uri_prefix: /images/shops
            upload_destination: '%kernel.project_dir%/public/images/shops'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
